-- TABLE
CREATE TABLE IF NOT EXISTS ENSINO.TB_USUARIO
(
    ID BIGINT NOT NULL,
    EMAIL CHARACTER VARYING(80) NOT NULL,
    NOME CHARACTER VARYING(100) NOT NULL,
    HASH_SENHA CHARACTER VARYING(60) NOT NULL,
    DATA_CADASTRO TIMESTAMP WITH TIME ZONE NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP WITH TIME ZONE,
    ID_USUARIO_CRIACAO BIGINT NOT NULL,
    ID_USUARIO_ATUALIZACAO BIGINT,
    ATIVO BOOLEAN NOT NULL,
    FUSO_HORARIO CHARACTER VARYING(50)
);

-- COMMENT
COMMENT ON COLUMN ENSINO.TB_USUARIO.ID IS 'CÓDIGO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.EMAIL IS 'E-MAIL DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.NOME IS 'NOME DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.HASH_SENHA IS 'HASH DA SENHA DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.DATA_CADASTRO IS 'DATA DE CADASTRO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.DATA_ATUALIZACAO IS 'DATA DE ATUALIZAÇÃO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.ID_USUARIO_CRIACAO IS 'USUÁRIO DE CRIAÇÃO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.ID_USUARIO_ATUALIZACAO IS 'USUÁRIO DE ATUALIZAÇÃO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.ATIVO IS '[TRUE/FALSE] - SINALIZAÇÃO DE ATIVO DO USUÁRIO';
COMMENT ON COLUMN ENSINO.TB_USUARIO.FUSO_HORARIO IS 'FUSO HORÁRIO DO USUÁRIO';

-- PRIMARY KEY
ALTER TABLE ENSINO.TB_USUARIO ADD CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID);

-- UNIQUE
ALTER TABLE ENSINO.TB_USUARIO ADD CONSTRAINT UQ_TB_USUARIO_1 UNIQUE (EMAIL);
